main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
    path('sales/', views.sales, name="sales"),
    path('misu_download', views.misu_download, name="misu_download"),
    path('delete', views.delete_func, name="delete"),
    path('tmp/', views.tmp, name="tmp"),
]

qooqoo_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('employee/', include("employee.urls")),
    path('trade/', include("trade.urls")),
]

trade/urls.py
from django.urls import path
from . import views

app_name = "trade"

urlpatterns = [
    path('client/', views.client, name="client"),
    path('client/getclient', views.getClient, name="getClient"),
    path('client/trade', views.clientTrade, name="clientTrade"),
    path('client/trade/get', views.getClientTrade, name="getClientTrade"),
    path('client/trade/edit', views.editTrade, name="editTrade"),
    path('client/trade/gettrade', views.getTrade, name="getTrade"),

    path('fix/', views.fix, name="fix"),
    path('fix/getFix', views.getFix, name="getFix"),
    path('fix/cost', views.fixCost, name="fixCost"),
    path('fix/cost/getCost', views.getFixCost, name="getFixCost"),

    path('manage/', views.manage, name="manage"),
    path('manage/getmanage', views.getManage, name="getmanage"),

    path('royalty/', views.royalty, name="royalty"),
    path('royalty/getRoyalty', views.getRoyalty, name="getRoyalty"),

    path('rant/', views.rant, name="rant"),
    path('rant/getrant', views.getRant, name="getRant"),
    path('rant/pay', views.rantPay, name="rantPay"),
    path('rant/pay/getRantPay', views.getRantPay, name="getRantPay"),

    path('etc/', views.etc, name="etc"),
    path('client/getetc', views.getEtc, name="getEtc"),

    path('etc/pay', views.etcPay, name="etcPay"),
    path('etc/pay/getPay', views.getEtcPay, name="getEtcPay"),

    path('cardinfo', views.cardinfo, name="cardinfo"),
    path('cardinfo/getinfo', views.getCardInfo, name="getcardinfo"),

    path('card', views.cardcost, name='cardcost'),
    path('card/getCost', views.getCardCost, name='getcardcost'),
]

trade/models.py
from django.db import models

# Create your models here.

class Client(models.Model):
    client = models.CharField(max_length=40)
    regnum = models.CharField(max_length=20)
    event = models.CharField(max_length=20)
    bank = models.CharField(max_length=20)
    banknum = models.CharField(max_length=20)
    callnum = models.CharField(max_length=20)
    is_card = models.IntegerField()
    status = models.CharField(max_length=10)

class ClientTrade(models.Model):
    date = models.DateField()
    client = models.CharField(max_length=40)
    price = models.IntegerField()
    pay = models.IntegerField()
    card = models.IntegerField(default=0)
    content = models.TextField()

class Fix(models.Model):
    fix = models.CharField(max_length=50)
    event = models.CharField(max_length=30)
    paytype = models.CharField(max_length=15)

class FixCost(models.Model):
    date = models.DateField()
    fix = models.CharField(max_length=50)
    price = models.IntegerField()
    pay = models.IntegerField()
    content = models.TextField()

class Rant(models.Model):
    rant = models.CharField(max_length=40)
    landload = models.CharField(max_length=20)
    bank = models.CharField(max_length=20)
    banknum = models.CharField(max_length=20)
    pay = models.CharField(max_length=20)
    surtax = models.CharField(max_length=20)
    content = models.TextField()

class RantPay(models.Model):
    date = models.DateField()
    rant = models.CharField(max_length=50)
    price = models.IntegerField()
    pay = models.IntegerField()
    content = models.TextField()

class Etc(models.Model):
    summary = models.CharField(max_length=50)
    etc = models.CharField(max_length=40)
    pay = models.IntegerField()
    paytype = models.CharField(max_length=20)
    content = models.TextField()

class EtcPay(models.Model):
    date = models.DateField()
    summary = models.CharField(max_length=50)
    etc = models.CharField(max_length=40)
    price = models.IntegerField()
    pay = models.IntegerField()
    paytype = models.CharField(max_length=20)
    content = models.TextField()

class Royalty(models.Model):
    date = models.DateField()
    royalty = models.CharField(max_length=50)
    price = models.IntegerField()
    pay = models.IntegerField()
    content = models.TextField()

class Manage(models.Model):
    date = models.DateField()
    price = models.IntegerField()
    status = models.CharField(max_length=20)
    content = models.TextField()

class CardInfo(models.Model):
    card = models.CharField(max_length=30)
    content = models.TextField()

class CardCost(models.Model):
    date = models.DateField()
    card = models.CharField(max_length=30)
    cost = models.IntegerField()
    content = models.TextField()

trade/views.py
from django.shortcuts import render, redirect
from .models import *
from django.core import serializers
from django.http import HttpResponse
from main.utils import *
from main.editdate import *
import datetime


def client(request):
    if request.method == "POST":
        data = getPOSTValue(request.POST)
        is_empty = Client.objects.filter(id=data[0])

        if is_empty:
            model = Client.objects.get(id=data[0])
        else:
            model = Client()

        model.client = data[1]
        model.regnum = data[2]
        model.event = data[3]
        model.bank = data[4]
        model.banknum = data[5]
        model.callnum = data[6]
        model.is_card = data[7]
        model.status = data[8]
        model.save()

        return redirect("trade:client")
    datas = Client.objects.all()
    context = {
        'datas' : datas,
    }
    return render(request, "trade/client.html", context)

def getClient(request):
    key = request.GET.get("key")
    data = Client.objects.filter(id=key)
    post_list = serializers.serialize('json', data)
    return HttpResponse(post_list, content_type="text/json-comment-filtered")

def clientTrade(request):
    if request.method == "POST":
        client = request.POST.get("client")
        date = request.POST.getlist("date[]")
        price = request.POST.getlist("price[]")
        content = request.POST.getlist("content[]")

        for i in range(len(date)):
            if price[i] == "" or price[i] == "0":
                continue
            trade = ClientTrade.objects.filter(client=client, date=date[i], price__gt=0)

            if(len(trade)):
                model = ClientTrade.objects.get(client=client, date=date[i], price__gt=0)

                model.content = content[i]
                model.price = price[i]

            else:
                model = ClientTrade()

                model.client = client
                model.date = date[i]
                model.price = price[i]
                model.pay = 0
                model.content = content[i]

            model.save()

        return redirect("trade:clientTrade")


    date = datetime.datetime.now().strftime("%Y-%m-%d")

    filter_client = request.GET.get("client", "all")
    filter_start = request.GET.get("start", "1000-01") + "-01"
    filter_end = request.GET.get("end", "9999-12")

    filter_end += f"-{str(getLastDatOfTheMonth(int(filter_end.split('-')[0]), int(filter_end.split('-')[1])))}"

    if filter_client == "all":
        trading = ClientTrade.objects.filter(date__range=[filter_start, filter_end]).order_by("-date")
        misu_chk = ClientTrade.objects.all()
    else:
        trading = ClientTrade.objects.filter(client=filter_client, date__range=[filter_start, filter_end]).order_by("-date")
        misu_chk = ClientTrade.objects.filter(client=filter_client).all()

    total = 0
    select_total = 0
    for trade in trading:
        select_total += trade.price

    for trade in misu_chk:
        total += trade.price - trade.pay

    client = Client.objects.values("client")

    context = {
        'today': datetime.datetime.strptime(date, "%Y-%m-%d"),
        'clients': client,
        'datas': trading,
        'select_total': select_total,
        'misu': total,
        'filter_client': filter_client,
    }
    if filter_start.split("-")[0] != "1000":
        context["filter_start"] = datetime.datetime.strptime(filter_start, "%Y-%m-%d")
        context["filter_end"] = datetime.datetime.strptime(filter_end, "%Y-%m-%d")

    print(date, context["today"])

    return render(request, "trade/client_trade.html", context)

def editTrade(request):
    if request.method == "POST":
        data = getPOSTValue(request.POST)
        model = ClientTrade.objects.filter(id=data[0])

        if len(model) == 0:
            model = ClientTrade()
        else:
            model = ClientTrade.objects.get(id=data[0])

        model.date = data[1]
        model.client = data[2]
        model.price = data[3]
        model.pay = data[4]
        model.content = data[5]
        model.card = data[6]
        model.save()

    return redirect("trade:clientTrade")

def getClientTrade(request):
    key = request.GET.get("key")
    data = ClientTrade.objects.filter(id=key)
    post_list = serializers.serialize('json', data)
    return HttpResponse(post_list, content_type="text/json-comment-filtered")

def getTrade(request):
    client = request.GET.get("client")
    month = request.GET.get("month")
    input = month.split("-")
    start = f"{input[0]}-{input[1]}-01"
    end = f"{input[0]}-{input[1]}-{getLastDatOfTheMonth(int(input[0]), int(input[1]))}"
    data = ClientTrade.objects.filter(client=client, date__range=[start, end], price__gt=0)
    post_list = serializers.serialize('json', data)
    return HttpResponse(post_list, content_type="text/json-comment-filtered")

def fix(request):
    if request.method == "POST":
        data = getPOSTValue(request.POST)
        is_empty = Fix.objects.filter(id=data[0])

        if is_empty:
            model = Fix.objects.get(id=data[0])
        else:
            model = Fix()

        model.fix = data[1]
        model.event = data[2]
        model.paytype = data[3]
        model.save()

        return redirect("trade:fix")

    datas = Fix.objects.all()

    context = {
        'datas' : datas,
    }
    return render(request, "trade/fixcost.html", context)

def getFix(request):
    key = request.GET.get("key")
    data = Fix.objects.filter(id=key)
    post_list = serializers.serialize('json', data)
    return HttpResponse(post_list, content_type="text/json-comment-filtered")

def fixCost(request):
    if request.method == "POST":
        data = getPOSTValue(request.POST)
        is_empty = FixCost.objects.filter(id=data[0])
        target = Fix.objects.get(fix=data[2])

        if is_empty:
            model = FixCost.objects.get(id=data[0])
        else:
            model = FixCost()

        model.date = data[1] + "-01"
        model.fix = data[2]

        if target.paytype == "자동이체":
            model.price = data[3]
            model.pay = data[3]
        else:
            print(data[4])
            if data[4] == "1":
                model.price = data[3]
                model.pay = data[3]
            else:
                model.price = data[3]
                model.pay = 0

        model.content = data[5]
        model.save()

        return redirect("trade:fixCost")

    fix = Fix.objects.all()
    datas = FixCost.objects.all()
    context = {
        'fix': fix,
        'datas': datas,
    }
    return render(request, "trade/fixTrade.html", context)


def getFixCost(request):
    key = request.GET.get("key")
    data = FixCost.objects.filter(id=key)
    post_list = serializers.serialize('json', data)
    return HttpResponse(post_list, content_type="text/json-comment-filtered")

def royalty(request):
    if request.method == "POST":
        data = getPOSTValue(request.POST)
        is_empty = Royalty.objects.filter(id=data[0])

        if is_empty:
            model = Royalty.objects.get(id=data[0])
        else:
            model = Royalty()

        model.date = data[1] + "-01"
        model.royalty = data[2]
        model.price = data[3]
        model.pay = data[4]
        model.content = data[5]
        model.save()

        return redirect("trade:royalty")

    start = request.GET.get("start", "-1")

    if start != "-1":
        datas = Royalty.objects.filter(date__year=start).all()
    else:
        datas = Royalty.objects.all()

    context = {
        'datas': datas,
        "start": start,
    }
    return render(request, "trade/royalty.html", context)

def getRoyalty(request):
    key = request.GET.get("key")
    data = Royalty.objects.filter(id=key)
    post_list = serializers.serialize('json', data)
    return HttpResponse(post_list, content_type="text/json-comment-filtered")


def rant(request):
    if request.method == "POST":
        data = getPOSTValue(request.POST)
        is_empty = Rant.objects.filter(id=data[0])

        if is_empty:
            model = Rant.objects.get(id=data[0])
        else:
            model = Rant()

        model.rant = data[1]
        model.landload = data[2]
        model.bank = data[3]
        model.banknum = data[4]
        model.pay = data[5]
        model.surtax = data[6]
        model.content = data[7]
        model.save()

        return redirect("trade:rant")

    datas = Rant.objects.all()
    context = {
        'datas' : datas,
    }
    return render(request, "trade/rant.html", context)


def getRant(request):
    key = request.GET.get("key")
    data = Rant.objects.filter(id=key)
    post_list = serializers.serialize('json', data)
    return HttpResponse(post_list, content_type="text/json-comment-filtered")

def rantPay(request):
    if request.method == "POST":
        data = getPOSTValue(request.POST)
        is_empty = RantPay.objects.filter(id=data[0])

        if is_empty:
            model = RantPay.objects.get(id=data[0])
        else:
            model = RantPay()

        model.date = data[1]
        model.rant = data[2]
        model.price = data[3]
        model.pay = data[4]
        model.content = data[5]
        model.save()

        return redirect("trade:rantPay")

    rants = Rant.objects.all()
    datas = RantPay.objects.all()

    context = {
        'rants': rants,
        'datas': datas,
    }
    return render(request, "trade/rantPay.html", context)

def getRantPay(request):
    key = request.GET.get("key")
    data = RantPay.objects.filter(id=key)
    post_list = serializers.serialize('json', data)
    return HttpResponse(post_list, content_type="text/json-comment-filtered")

def etc(request):
    if request.method == "POST":
        data = getPOSTValue(request.POST)
        is_empty = Etc.objects.filter(id=data[0])

        if is_empty:
            model = Etc.objects.get(id=data[0])
        else:
            model = Etc()

        model.etc = data[1]

templates/trade/cardcost.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <div>
        <div class="input-area">
            <form method="post">
                {% csrf_token %}
                <div class="input-form">
                    <input type="hidden" id="id" name="id" value="-1">
                    <div><label>날짜</label><input type="month" data-placeholder="날짜선택" name="date" id="date" required></div>
                    <div><label>카드사</label><input type="text" name="card" id="card" required></div>
                    <div><label>금액</label><input type="text" name="cost" id="cost" required></div>
                    <div><label>비고</label><input type="text" name="content" id="content"> </div>
                </div>
                <div class="submit-form">
                    <input type="submit" value="저장">
                    <input type="button" value="삭제" id="delete">
                <div><input type="button" value="초기화" onclick="location.href='';"></div>
                </div>
            </form>
        </div>
        <div class="null-area">
        </div>
        <div class="view-area">
            <div class="view-header">
                <h1>카드대금 입력</h1>
            </div>

            <div style="border : 1px solid black; height : 35rem; overflow: auto;">
                <div id="data-fields">

                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var dataHeader = ["날짜", "카드사", "금액", "비고"];
        var datas = []
        var dataId = "#data-fields";
        let db = "cardcost";

        {% for data in datas %}
            var line = [];

            line.push("{{ data.id }}");
            line.push("{{ data.date|date:'Y년 m월' }}");
            line.push("{{ data.card }}");
            line.push("{{ data.cost|intcomma }} 원");
            line.push("{{ data.content }}");
            datas.push(line)
        {% endfor %}

        gridSetting(dataId, 1);
        printData(1, dataId, dataHeader, datas);

        $(document).on("click", ".data-body", function () {
            var findkey = $(this).children("div:eq(0)");
            var key = findkey.get()[0].innerText;
            var getValue = getData(key, "{% url 'trade:getcardcost' %}");
            getValue["date"] = getValue["date"].slice(0, 7)
            formSetData(getValue, key);
        });

    </script>
{% endblock %}

templates/trade/cardinfo.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <div>
        <div class="input-area">
            <form method="post">
                {% csrf_token %}
                <div class="input-form">
                    <input type="hidden" id="id" name="id" value="-1">
                    <div><label>카드사</label><input type="text" name="card" id="card" required></div>
                    <div><label>비고</label><input type="text" name="content" id="content"> </div>
                </div>
                <div class="submit-form">
                    <input type="submit" value="저장">
                    <input type="button" value="삭제" id="delete">
                    <input type="button" value="초기화" onclick="history.go()">
                </div>
            </form>
        </div>
        <div class="null-area">
        </div>
        <div class="view-area">
            <div class="view-header">
                <h1>카드정보관리</h1>
            </div>

            <div style="border : 1px solid black; height : 35rem; overflow: auto;">
                <div id="data-fields">

                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var dataHeader = ["카드사", "비고"];
        var datas = []
        var dataId = "#data-fields";
        let db = "cardinfo";

        {% for data in datas %}
            var line = [];
            line.push("{{ data.id }}");
            line.push("{{ data.card }}");
            line.push("{{ data.content }}");
            datas.push(line)
        {% endfor %}

        gridSetting(dataId, 1);
        printData(1, dataId, dataHeader, datas);

        $(document).on("click", ".data-body", function () {
            var findkey = $(this).children("div:eq(0)");
            var key = findkey.get()[0].innerText;
            var getValue = getData(key, "{% url 'trade:getcardinfo' %}");

            formSetData(getValue, key);
        });
    </script>
{% endblock %}

templates/trade/client_trade.html
{% extends 'base.html' %}
{% load static %}
{% load mathfilters %}
{% load humanize %}
{% load customfilter %}
{% block content %}
    <link href="{% static 'css/modal.css' %}" rel="stylesheet" type="text/css">
    <div class="input-area">
        <form method="post" action="{% url 'trade:editTrade' %}">
            <div class="input-form">
                {% csrf_token %}
                <input type="hidden" name="id" id="id" value="-1">
                <div><label>날짜</label><input type="date" name="date" id="date" required></div>
                <div><label>거래처명</label>
                    <select name="client" id="client" required>
                        {% for client in clients %}
                            <option value="{{ client.client }}">{{ client.client }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div><label>거래금액</label><input type="number" name="price" id="price" min="0" value="0" readonly></div>
                <div><label>납입금액</label><input type="text" name="pay" id="pay" min="0" required></div>
                <div><label>비고</label><input type="text" name="content" id="content"></div>
            </div>
            <div class="submit-form">
                <div><input type="submit" value="저장"></div>
                    <input type="button" value="삭제" id="delete">
                <div><input type="button" value="초기화" onclick="history.go();"></div>
            </div>
        </form>
    </div>
    <div class="null-area">
    </div>
    <div style="margin : 1rem;"></div>
    <div class="view-area">
        <div class="view-header"><h1>거래내역관리</h1><span><button class="input-button">거래입력</button></span></div>
        <div class="input-area" id="batch-form">
            <form method="get">
                <div class="input-form" style="width : 100%;">
                    <div>필터기능</div>
                    <div><label>거래처</label>
                        <select id="batch-client" name="client" required>
                            <option value="all">전체</option>
                            {% for client in clients %}
                                {% if filter_client == client.client %}
                                    <option value="{{ client.client }}" selected>{{ client.client }}</option>
                                {% else %}
                                    <option value="{{ client.client }}">{{ client.client }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <div><label>시작</label><input type="month" name="start" value="{{ filter_start|date:'Y-m' }}" required></div>
                    <div><label>종료</label><input type="month" name="end" value="{{ filter_end|date:'Y-m' }}" required></div>
                    <input type="submit" value="검색" id="search">
                <span style="float:right">조회 날짜 금액 : {{ select_total|intcomma }}원 | 총 미수금 : {{ misu|intcomma }}원 </span>
                </div>
            </form>
        </div>
        <div>
            <div style="border : 1px solid black; height : 35rem;">
                <div id="data-fields">
                </div>
            </div>
        </div>
    </div>


    <!-- modal -->
    <div id="modal" class="modal-overlay">
        <div class="modal-window">
            <div class="title">
                <h2>거래입력</h2>
            </div>
            <div class="close-area">X</div>
            <div class="content">
                <div class="search-fields">
                    <div><label>거래처</label>
                        <select id="search-client">
                            {% for client in clients %}
                                <option value="{{ client.client }}">{{ client.client }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div><label>선택월</label><input type="month" id="inputmonth"></div><button id="search-button">검색</button></div>
                <div class="search-header"><div>거래일자</div><div>거래금액</div><div>비고</div></div>
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="client" id="iclient" value="">
                    <div class="search-data"></div>
                    <input class="" type="submit" value="저장">
                </form>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var dataHeader = ["거래일자", "상호명", "금액", "상태", "비고", "납부방법"];
        var datas = [];
        var filterdatas = [];
        var dataId = "#data-fields";
        var sortfix = [0, 1];
        var filterValue =["{{ filter_client }}","{{ filter_start }}","{{ filter_end }}"];
        let db = "clienttrade";
        {% for data in datas %}
            var line = []
            line.push("{{ data.id }}");
            line.push("{{ data.date|date:"Y-m-d" }}");
            line.push("{{ data.client }}");
            line.push("{{ data.price|output_pay:data.pay|intcomma }} 원");
            line.push("{{ data.price|output_type }}");
            line.push("{{ data.content }}");
            line.push("{{ data.card|is_card }}");
            datas.push(line);
        {% endfor %}

        gridSetting(dataId, 1);
        printData(1, dataId, dataHeader, datas);

        $(document).on("click", ".data-header .datas", function() {
            var sortkey = $(".data-header .datas").index(this);

        });

        $(document).on("click", ".data-body", function () {
            var findkey = $(this).children("div:eq(0)");
            var key = findkey.get()[0].innerText;
            var getValue = getData(key, "{% url 'trade:getClientTrade' %}");
            formSetData(getValue, key);
        });

        $(document).on("click", ".input-button", function(){
            $("#inputmonth").val("{{ today|date:'Y-m' }}");
            $("#data-fields .data-header").css("z-index", "0");
            $("#modal.modal-overlay").css("visibility", "visible");
        });

        $(document).on("click", ".close-area", function(){
            $(".search-data").empty();
            $("#modal.modal-overlay").css("visibility", "hidden");
            $("#data-fields .data-header").css("z-index", "1");
        });

        $(document).on("click", "#search-button", function(){
            let lastdays = [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

            var client = $("#search-client").val();
            var m = $("#inputmonth").val();
            var x = m.split("-")
            var start = m + "-01";
            if(x[1] == 2) {
                if(x[0] % 400 == 0) var end = m + "-" + lastdays[parseInt(x[1])] + 1;
                else if(x[0] % 100 == 0) var end = m + "-" + lastdays[parseInt(x[1])];
                else if(x[0] % 4 == 0) var end = m + "-" + lastdays[parseInt(x[1])];
            }
            else {
                var end = m + "-" + lastdays[parseInt(x[1])];
            }
            var dateList = getDatesStartToLast(start, end);
            var dateValue = getTradeValue(client, m, "{% url 'trade:getTrade' %}");
            $("#iclient").val(client);
            $(".search-data").empty();
            for (date of dateList) {
                var c = 1
                for (data of dateValue) {
                    if (data["date"] == date) {
                        var line = "<div class='searched'><div><input type='date' name='date[]' value='" + date + "' readonly tabindex='-1'></div><div><input type='number' name='price[]' value='" + data["price"] + "'></div><div><input type='text' name='content[]' value='" + data["content"] + "' tabindex='-1'></div></div>";
                        $(".search-data").append(line);
                        c = 0;
                    }
                }
                if(c) {
                    var line = "<div class='searched'><div><input type='date' name='date[]' value='" + date + "' readonly tabindex='-1'></div><div><input type='number' name='price[]'></div><div><input type='text' name='content[]' tabindex='-1'></div></div>";
                    $(".search-data").append(line);
                }
            }
        });
        $(document).on("click", ".data-header .datas", function() {
            var sortkey = $(".data-header .datas").index(this);
            if(sortkey == sortfix[0]){
                if(sortfix[1] == 1){
                    datas = sorting(datas, sortkey);
                    sortfix[1] = 0;

                    clearlist();
                    gridSetting(dataId, 1);
                    printData(0, dataId, dataHeader, datas);
                } else {
                    datas = sorting(datas, sortkey);
                    datas.reverse();
                    sortfix[1] = 1;

                    clearlist();
                    gridSetting(dataId, 1);
                    printData(0, dataId, dataHeader, datas);
                }
            }else {
                datas = sorting(datas, sortkey);
                datas.reverse();
                sortfix[0] = sortkey;
                sortfix[1] = 0;

                clearlist();
                gridSetting(dataId, 1);
                printData(0, dataId, dataHeader, datas);
            }
        });

    </script>
{% endblock %}

templates/trade/utilitybill.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>