main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
    path('sales/', views.sales, name="sales"),
    path('misu_download', views.misu_download, name="misu_download"),
    path('delete', views.delete_func, name="delete"),
    path('tmp/', views.tmp, name="tmp"),
]

qooqoo_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('employee/', include("employee.urls")),
    path('trade/', include("trade.urls")),
]

main/models.py
from django.db import models

class Sales(models.Model):
    month = models.DateField()
    price = models.IntegerField()

class Banks(models.Model):
    bank = models.CharField(max_length=30)

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .reporting import tradeReport, SQL
from datetime import datetime, timedelta
from django.db import connection
from .crawling import *
from .models import *

import pandas as pd

try:
    from io import BytesIO as IO  # for modern python
except ImportError:
    from io import StringIO as IO  # for legacy python

from trade.models import *
from employee.models import *

def get_exceldownload(df):
    excel_file = IO()
    xlwriter = pd.ExcelWriter(excel_file, engine='xlsxwriter')

    df.to_excel(xlwriter, 'sheetname')
    xlwriter.save()
    xlwriter.close()
    excel_file.seek(0)
    response = HttpResponse(excel_file.read(), content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename ="foo.xlsx"'
    return response

def a_few_months_ago(year, month, n):
    return f"{str(year - 1)}-{str(month + 12 - n).rjust(2, '0')}-01" if month - n <= 0 else f"{str(year)}-{str(month - n).rjust(2, '0')}-01"


def profit_or_loss():
    sql = SQL()
    m_2 = a_few_months_ago(datetime.now().year, datetime.now().month, 2)
    m_1 = a_few_months_ago(datetime.now().year, datetime.now().month, 1)
    m_0 = a_few_months_ago(datetime.now().year, datetime.now().month, 0)

    dist = {m_2: 0, m_1: 0, m_0: 0}
    labor = {m_2: 0, m_1: 0, m_0: 0}
    card = {m_2: 0, m_1: 0, m_0: 0}
    fix = {m_2: 0, m_1: 0, m_0: 0}
    royalty = {m_2: 0, m_1: 0, m_0: 0}
    profit = {m_2: 0, m_1: 0, m_0: 0}
    rant = {m_2: 0, m_1: 0, m_0: 0}
    manage = {m_2: 0, m_1: 0, m_0: 0}
    etc = {m_2: 0, m_1: 0, m_0: 0}

    two_month_ago = a_few_months_ago(datetime.now().year, datetime.now().month, 2)

    #매출
    query = f"select strftime('%Y-%m', month) as month, sum(price) as price from main_sales where month >= '{two_month_ago}' group by month order by month desc limit 3";
    res = sql.select(query)
    if res:
        for r in res:
            profit[r[0]+"-01"] = r[1]

    #물류
    query = f"select strftime('%Y-%m', trade.date) as month, sum(trade.price) as price from trade_client client, trade_clientTrade trade where client.client = trade.client and client.is_card = 0 and trade.date >= '{two_month_ago}' group by month order by month desc limit 3";
    res = sql.select(query)
    if res:
        for r in res:
            dist[r[0]+"-01"] = r[1]

    #인건비
    query = f"select strftime('%Y-%m', date) as month, sum(cost) as price from employee_laborCost where date >= '{two_month_ago}' group by month order by month desc limit 3";
    res = sql.select(query)
    if res:
        for r in res:
            labor[r[0]+"-01"] = r[1]

    #고정비
    query = f"select strftime('%Y-%m', date) as month, sum(price) as price from trade_fixCost where date >= '{two_month_ago}' group by month order by month desc limit 3";
    res = sql.select(query)
    if res:
        for r in res:
            fix[r[0]+"-01"] = r[1]

    #로열티
    query = f"select strftime('%Y-%m', date) as month, sum(price) as price from trade_royalty where date >= '{two_month_ago}' group by month order by month desc limit 3";
    res = sql.select(query)
    if res:
        for r in res:
            royalty[r[0]+"-01"] = r[1]

    #기타
    query = f"select strftime('%Y-%m', etcpay.date) as month, sum(etcpay.price) as price from trade_etc etc, trade_etcPay etcpay where etcpay.date >= '{two_month_ago}' and etc.paytype = '수기납부' group by month order by month desc limit 3";
    res = sql.select(query)
    if res:
        for r in res:
            etc[r[0]+"-01"] = r[1]

    #관리비
    query = f"select strftime('%Y-%m', date) as month, sum(price) from trade_manage where date >= '{two_month_ago}' group by month order by month desc limit 3";
    res = sql.select(query)
    if res:
        for r in res:
            manage[r[0]+"-01"] = r[1]

    #임대료
    query = f"select strftime('%Y-%m', date) as month, sum(price) as price from trade_rantpay where date >= '{two_month_ago}' group by month order by month desc limit 3";
    res = sql.select(query)
    if res:
        for r in res:
            rant[r[0]+"-01"] = r[1]

    #카드대금
    query = f"select strftime('%Y-%m', date) as month, sum(cost) as price from trade_cardCost where date >= '{two_month_ago}' group by month order by month desc limit 3";
    res = sql.select(query)
    if res:
        for r in res:
            card[r[0]+"-01"] = r[1]

    # profit or loss
    result = [0, 0, 0]
    if len(profit) >= 3:
        for i, d in enumerate([m_0, m_1, m_2]):
            result[i] = profit[d] - dist[d] - labor[d] - card[d] - rant[d] - manage[d] - etc[d] - fix[d] - royalty[d]

    return result

def month3(year, month):
    return [f"{str(year-1)}년 {str(month+12-2)}월" if month-2 <= 0 else f"{str(year)}년 {str(month-2)}월",
            f"{str(year-1)}년 {str(month+12-1)}월" if month-1 <= 0 else f"{str(year)}년 {str(month-1)}월",
            f"{str(year)}년 {str(month)}월"]


def index(request):
    two_month_ago = a_few_months_ago(datetime.now().year, datetime.now().month, 2)

    selected = request.GET.get("selected", "매출")
    sql = SQL()
    datas = list()
    if selected == "매출":
        query = f"select strftime('%Y-%m', month) as group_month, sum(price) as price from main_sales where month >= '{two_month_ago}' group by group_month order by group_month desc limit 3";

    elif selected == "물류":
        query = f"select strftime('%Y-%m', date) as month, sum(price) as price from trade_clientTrade where date >= '{two_month_ago}' group by month order by month desc limit 3";

    elif selected == "인건비":
        query = f"select strftime('%Y-%m', date) as month, sum(cost) as price from employee_laborCost where date >= '{two_month_ago}'group by month order by month desc limit 3";

    elif selected == "법인카드":
        query = f"select strftime('%Y-%m', date) as month, sum(cost) as price from trade_cardCost where date >= '{two_month_ago}' group by month order by month desc limit 3";

    res = sql.select(query)

    if res:
        for r in res:
            datas.append({'month': datetime.strptime(r[0]+"-01", "%Y-%m-%d"), 'price': r[1]})
        while len(datas) < 3:
            datas.insert(0, {'month': datetime.now(), 'price': 0})

    profitorloss = profit_or_loss()
    report = tradeReport()

    client_misu = report.client_misu()
    fix_misu = report.fix_misu()
    royal_misu = report.royal_misu()
    manage_misu = report.manage_misu()
    rant_misu =report.rant_misu()

    context = {
        #graph
        'profitorloss': profitorloss,
        'selected': selected,
        'datas':datas,

        #misu
        'misu_clients': client_misu,
        'misu_fixs': fix_misu,
        'misu_royals': royal_misu,
        'misu_manages': manage_misu,
        'misu_rants': rant_misu,
    }
    return render(request, "main/index.html", context)

def insert_sales(sales):
    for sale in sales:
        try:
            model = Sales.objects.filter(month=sale[0] + "-01")
            if len(model):
                model = Sales.objects.get(month=sale[0] + "-01")
                if model.price == sale[1]:
                    continue
            else:
                model = Sales()

            model.month = sale[0] + "-01"
            model.price = sale[1]
            model.save()
        except:
            pass

def sales(request):
    if request.method == "POST":

        id = request.POST.get("id")
        pw = request.POST.get("pw")

        data = web_crawling(id, pw)
        insert_sales(data)

        return redirect("main:sales")

    datas = Sales.objects.all()
    context = {
        'datas': datas,
    }
    return render(request, "main/sales.html", context)

def model_to_cecel(model):
    params = None

    if model == "client":
        sql = ("select"
               " client.client as '거래처',"
               " client.regnum as '사업자등록번호',"
               " client.event as '종목',"
               " client.bank as '은행',"
               " client.banknum as '계좌번호',"
               " client.callnum as '연락처',"
               " client.status as '계약상태',"
               " sum(trade.price-trade.pay) as '미수금'"
               " from trade_client client, trade_clientTrade trade"
               " where client.client = trade.client and"
               " trade.price - trade.pay > 0 and"
               " client.is_card = 0"
               " group by client.client")

    elif model == "fix":
        sql = ("select"
               " fix.fix as '고정비명',"
               " fix.event as '종목',"
               " fix.paytype as '납부타입',"
               " sum(cost.price-cost.pay) as '미수금'"
               " from trade_fix fix, trade_fixCost cost"
               " where fix.fix=cost.fix and"
               " cost.price - cost.pay > 0"
               " group by cost.fix")

    elif model == "royalty":
        sql = ("select"
               " date as '날짜',"
               " royalty as '로열티',"
               " (price - pay) as '미수금',"
               " content as '비고'"
               " from trade_royalty"
               " where (price - pay) > 0 order by date")

    elif model == "manage":
        sql = ("select"
               " strftime('%Y년 %m월', date) as '날짜',"
               " price as '미수금',"
               " content as '비고'"
               " from trade_manage"
               " where status='미납'")

    elif model == "rant":
        sql = ("select"
               " rant.rant as '호수',"
               " rant.landload as '임대인',"
               " rant.bank as '은행',"
               " rant.banknum as '계좌번호',"
               " sum(pay.price - pay.pay) as '미납임대료'"
               " from trade_rant rant, trade_rantpay pay"
               " where rant.rant=pay.rant and"
               " pay.price - pay.pay > 0"
               " group by pay.rant")

    df = pd.read_sql_query(sql, connection, params=params)
    return df

def misu_download(request):
    misu = request.GET.get("target", "-1")
    if misu == "-1":
        return redirect("main:index")

templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% load customfilter %}
{% block content %}
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
    <link href="{% static 'css/dashboard.css' %}" type="text/css" rel="stylesheet"/>
    <div class="view-area">
        <div class="view-header dashboard-header"><h1>대시보드</h1></div>
        <div class="dashboard-main">
            <div class="null-box">
                <div class="sonic-graph">
                    <div class="dashboard-sub-title"><span class="material-symbols-outlined" style="vertical-align: bottom; margin-left:2rem; margin-right : 0.5rem; color:var(--primary-color);">bar_chart</span>손익그래프
                    </div>
                    <div class="select-box">
                        <label>선택</label>
                        <select id="selected">
                            <option value="매출">매출</option>
                            <option value="물류">물류</option>
                            <option value="인건비">인건비</option>
                            <option value="법인카드">법인카드</option>
                        </select>
                    </div>
                    <div class="content">
                        <canvas id="graph"></canvas>
                        <div id="sonic-data">
                            <div>
                                <div class="sonic-title">전전월 손익</div>
                                <div>
                                    {% if profitorloss.2|div:100_000_000 %}
                                        <span class="sonic-pay">{{ profitorloss.2|is_uk }}</span>
                                        <span class="sonic-unit">억</span>
                                    {% endif %}
                                    <span class="sonic-pay">{{ profitorloss.2|convert_pay }}</span><span
                                        class="sonic-unit">만원</span>
                                </div>
                                <div><span class="sonic-compare">당월대비</span>
                                    {% if profitorloss.2|sub:profitorloss.0 > 0 %}
                                        <span class="sonic-compare-pay red"> +
                                            {{ profitorloss.2|sub:profitorloss.0|print_pay }}만원</span>
                                    {% else %}
                                        <span class="sonic-compare-pay blue">
                                            {{ profitorloss.2|sub:profitorloss.0|print_pay }}만원</span>
                                    {% endif %}
                        </div>
                        </div>
                        <div>
                            <div class="sonic-title">전월 손익</div>
                            <div>
                                {% if profitorloss.1|div:100_000_000 > 0 %}
                                    <span class="sonic-pay">{{ profitorloss.1|is_uk }}</span>
                                    <span class="sonic-unit">억</span>
                                {% endif %}
                                <span class="sonic-pay">{{ profitorloss.1|convert_pay }}</span><span
                                    class="sonic-unit">만원</span></div>
                            <div><span class="sonic-compare">당월대비</span>
                                {% if profitorloss.1|sub:profitorloss.0 > 0 %}
                                    <span class="sonic-compare-pay red"> +
                                        {{ profitorloss.1|sub:profitorloss.0|print_pay }}만원</span>
                                {% else %}
                                    <span class="sonic-compare-pay blue">
                                        {{ profitorloss.0|sub:profitorloss.1|print_pay }}만원</span>
                                {% endif %}
                    </div>
                    </div>
                    <div>
                        <div class="sonic-title">당월 손익</div>
                        <div>
                            {% if profitorloss.0|div:100_000_000 > 0 %}
                                <span class="sonic-pay">{{ profitorloss.0|is_uk }}</span>
                                <span class="sonic-unit">억</span>
                            {% endif %}
                            <span class="sonic-pay">{{ profitorloss.0|convert_pay }}</span>
                            <span class="sonic-unit">만원</span></div>
                        <div><span class="sonic-compare">전월대비</span>
                            {% if profitorloss.0|sub:profitorloss.1 > 0 %}
                                <span class="sonic-compare-pay red"> +
                                    {{ profitorloss.0|sub:profitorloss.1|print_pay }}만원</span>
                            {% else %}
                                <span class="sonic-compare-pay blue">
                                    {{ profitorloss.0|sub:profitorloss.1|print_pay }}만원</span>
                            {% endif %}
                    </div>
                </div>
            </div>

            <div class="misu">
                <h1><span class="material-symbols-outlined" style="vertical-align: bottom; margin-right : 0.5rem; color:var(--primary-color);">bar_chart</span>미납내역</h1>
                <div class="misu-content">
                    <div class="misu-list">
                        <h3>거래처<span class="export" onclick="downloadExcel('client');">내보내기</span></h3>
                        <div class="data-column column-2"><div>거래처명</div><div>미수금</div></div>
                        <div class="datas">
                            {% for misu in misu_clients %}
                                <div class="column-2"><div>{{ misu.name }}</div><div>{{ misu.misu|intcomma }} 원</div></div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="misu-list">
                        <h3>고정비<span class="export" onclick="downloadExcel('fix');">내보내기</span></h3>
                        <div class="data-column column-2"><div>고정비명</div><div>미수금</div></div>
                        <div class="datas">
                            {% if misu_fixs %}
                                {% for misu in misu_fixs %}
                                    <div class="column-2"><div>{{ misu.name }}</div><div>{{ misu.misu|intcomma }} 원</div></div>
                                {% endfor %}
                            {% else %}
                                <div style="text-align : center;"><div>미수내역이 없습니다.</div></div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="misu-list">
                        <h3>로열티<span class="export" onclick="downloadExcel('royalty');">내보내기</span></h3>
                        <div class="data-column column-2"><div>날짜</div><div>미수금</div></div>
                        <div class="datas">
                            {% if misu_royals %}
                                {% for misu in misu_royals %}
                                    <div class="column-2"><div>{{ misu.name }}</div><div>{{ misu.misu|intcomma }} 원</div></div>
                                {% endfor %}
                            {% else %}
                                <div style="text-align : center;"><div>미수내역이 없습니다.</div></div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="misu-list">
                        <h3>관리비<span class="export" onclick="downloadExcel('manage');">내보내기</span></h3>
                        <div class="data-column column-2"><div>날짜</div><div>미수금</div></div>
                        <div class="datas">
                            {% if misu_manages %}
                                {% for misu in misu_manages %}
                                    <div class="column-2"><div>{{ misu.name|date:"Y년 m월" }}</div><div>{{ misu.misu|intcomma }} 원</div></div>
                                {% endfor %}
                            {% else %}
                                <div style="text-align : center;"><div>미수내역이 없습니다.</div></div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="misu-list">
                        <h3>임대료<span class="export" onclick="downloadExcel('rant');">내보내기</span></h3>
                        <div class="data-column column-2"><div>호수</div><div>미수금</div></div>
                        <div class="datas">
                            {% if misu_rants %}
                                {% for misu in misu_rants %}
                                    <div class="column-2"><div>{{ misu.name }}호</div><div>{{ misu.misu|intcomma }} 원</div></div>
                                {% endfor %}
                            {% else %}
                                <div style="text-align : center;"><div>미수내역이 없습니다.</div></div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        $("#selected").val("{{ selected }}");
        const ctx = document.getElementById('graph');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [
                    {% for data in datas reversed %}
                        '{{ data.month|date:"Y년 m월" }}',
                    {% endfor %}
                ],
                datasets: [{
                    label: "{{ selected }}",
                    data: [
                        {% for data in datas reversed %}
                            {{ data.price }},
                        {% endfor %}
                    ],
                    backgroundColor: ['#ff9900'],
                    borderColor: ['#EE7700'],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
        $(document).on("change", "#selected", function () {
            var f = $("#selected").val();
            console.log(f);
            location.href = "{% url 'main:index' %}?selected=" + f;
        });
        function downloadExcel(target) {
            console.log(target);
            location.href="{% url 'main:misu_download' %}?target="+target;
        }
    </script>
{% endblock %}

templates/main/report.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
    <link href="{% static 'css/report.css' %}" rel="stylesheet" type="text/css">
    <div class="input-area">
    </div>
    <div class="null-area">
    </div>
    <div class="view-area">
        <div class="view-header"><h1>레포트</h1></div>
        <div class="sub-title">1.미납현황</div>
        <div class="misu">
            <div class="sub-title">1.1 물류</div>
            <div class="misu-data">
                <div class="items data-header">
                    <div>거래처</div>
                    <div>미수금</div>
                </div>
                {% for misu in client_misus %}
                    <div class="items">
                        <div>{{ misu.name }}</div>
                        <div>{{ misu.misu|intcomma }}원</div>
                    </div>
                {% endfor %}
            </div>

            <div class="sub-title">1.2 고정비</div>
            <div class="misu-data">
                <div class="items data-header">
                    <div>거래처</div>
                    <div>미수금</div>
                </div>
                {% for misu in fix_misus %}
                    <div class="items">
                        <div>{{ misu.name }}</div>
                        <div>{{ misu.misu|intcomma }}원</div>
                    </div>
                {% endfor %}
            </div>
            <div class="sub-title">1.3 로열티</div>
            <div class="misu-data">
                <div class="items data-header">
                    <div>거래처</div>
                    <div>미수금</div>
                </div>
                {% for misu in fix_misus %}
                    <div class="items">
                        <div>{{ misu.name }}</div>
                        <div>{{ misu.misu|intcomma }}원</div>
                    </div>
                {% endfor %}
            </div>
            <div class="sub-title">1.4 관리비</div>
            <div class="misu-data">
                <div class="items data-header">
                    <div>거래처</div>
                    <div>미수금</div>
                </div>
                {% for misu in fix_misus %}
                    <div class="items">
                        <div>{{ misu.name }}</div>
                        <div>{{ misu.misu|intcomma }}원</div>
                    </div>
                {% endfor %}
            </div>
            <div class="sub-title">1.5 임대료</div>
            <div class="misu-data">
                <div class="items data-header">
                    <div>거래처</div>
                    <div>미수금</div>
                </div>
                {% for misu in fix_misus %}
                    <div class="items">
                        <div>{{ misu.name }}</div>
                        <div>{{ misu.misu|intcomma }}원</div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/main/sales.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% block content %}
    <link href="{% static 'css/sales.css' %}" type="text/css" rel="stylesheet"/>
    <div class="view-area">
        <div class="sales">

        <div class="view-header"><h1>매출관리</h1></div>
            <div class="crawling">
                <form method="post">
                    {% csrf_token %}
                    <div><label>아이디</label><input type="text" name="id" required></div>
                    <div><label>패스워드</label><input type="password" name="pw" required></div>
                    <div class="submit-button"><input type="submit" value="크롤링"></div>
                </form>
            </div>
            <div class="sales-table">
                <div class="data-header"><div>날짜</div><div>매출금액</div></div>
                {% for data in datas %}
                    <div class="data-body"><div>{{ data.month|date:"Y년 m월" }}</div><div>{{ data.price|intcomma }}원</div></div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/main/tmp..html
<html>
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <style>
        nav > .root {
            background : grey;
            color : white;
            padding : 1rem;
        }
        .root span:hover {
            background : #b68b8b;
        }
    </style>
    <script src="../../static/js/jquery-3.6.0.min.js"></script>
</head>
<body>
<nav>

    <ul class="root">
        <li class="items one">
            <span class="title">메뉴1</span>
            <ul>
                <li class="items two"><span class="title">서브메뉴1</span></li>
                <li class="items two"><span class="title">서브메뉴2</span></li>
            </ul>
        </li>
        <li class="items one">메뉴2</li>
        <li class="items one">
            <span class="title">메뉴3</span>
            <ul>
                <li class="items two"><span class="title">서브메뉴1</span></li>
                <li class="items two"><span class="title">서브메뉴2</span></li>
            </ul>
        </li>
        <li class="items one">메뉴4</li>
    </ul>
</nav>
<script>
    var navStatue = [[1],[0],[1],[0]];
    var cnt = 1;
    for(nav of navStatue){
        if(nav[0] == 0) {
            $(".root li:nth-child("+cnt+") > ul").css("display", "none");
        }else {
            $(".root li:nth-child("+cnt+") > ul").css("display", "block");
        }
        cnt++;
    }
</script>
</body>
</html>