employee/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "employee"

urlpatterns = [
                  path('employee', views.employee, name="employee"),
                  path('employee/getemployee', views.getemployee, name="getEmployee"),

                  path('parttimer', views.parttimer, name="parttimer"),
                  path('parttimer/getparttimer', views.getparttimer, name="getParttimer"),

                  path('oneday', views.oneday, name="oneday"),
                  path('oneday/getOneday', views.getOneday, name="getOneday"),

                  path('workemployee', views.workemployee, name="workEmployee"),
                  path('workemployee/getWork', views.getWorkEmployee, name="getWorkEmployee"),

                  path('workparttimer', views.workparttimer, name="workParttimer"),

                  path('workoneday', views.workoneday, name="workoneday"),
                  path('workoneday/getWork', views.getWorkOneday, name="getworkoneday"),

                  path('workReport', views.workReport, name="workReport"),
                  path('workReport/download', views.downloadWorkReport, name="downloadWorkReport"),

                  path('manageAnnual', views.manageAnnual, name="manageAnnual"),

                  path('laborCost', views.laborCost, name="laborCost"),
                  path('laborCost/get', views.getLaborCost, name="getLaborCost"),

                  path('employeeIO', views.employeeIO, name="employeeIO"),
                  path('IOdownload', views.IOdownload, name="IOdownload"),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
    path('sales/', views.sales, name="sales"),
    path('misu_download', views.misu_download, name="misu_download"),
    path('delete', views.delete_func, name="delete"),
    path('tmp/', views.tmp, name="tmp"),
]

qooqoo_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('employee/', include("employee.urls")),
    path('trade/', include("trade.urls")),
]

employee/models.py
from django.db import models
# Create your models here.

class Employee(models.Model):
    name = models.CharField(max_length=30)
    reg_num = models.CharField(max_length=30)
    contact = models.CharField(max_length=20)
    gender = models.CharField(max_length=10)
    bank = models.CharField(max_length=20)
    bank_num = models.CharField(max_length=30)
    inwork = models.DateField()
    outwork = models.DateField(null=True, blank=True)
    department = models.CharField(max_length=30)
    rank = models.CharField(max_length=30)
    worksystem = models.IntegerField()
    pay = models.IntegerField()
    insurance = models.CharField(max_length=20, null=True, blank=True)
    health = models.CharField(max_length=30)
    content = models.TextField()
    notreport = models.IntegerField()

class Parttimer(models.Model):
    name = models.CharField(max_length=30)
    reg_num = models.CharField(max_length=30)
    contact = models.CharField(max_length=20)
    gender = models.CharField(max_length=10)
    pay = models.IntegerField()
    bank = models.CharField(max_length=20)
    bank_num = models.CharField(max_length=30)
    department = models.CharField(max_length=30)
    part = models.CharField(max_length=30)
    inwork = models.DateField()
    outwork = models.DateField(null=True, blank=True)
    health = models.CharField(max_length=30)
    content = models.TextField()
    notreport = models.IntegerField()

class Oneday(models.Model):
    name = models.CharField(max_length=30)
    reg_num = models.CharField(max_length=30)
    contact = models.CharField(max_length=30)

class WorkStaff(models.Model):
    name = models.CharField(max_length=20)
    date = models.DateField()
    worktype = models.CharField(max_length=10)
    workstart = models.IntegerField()
    workend = models.IntegerField()
    breaktime = models.IntegerField(null=True, blank=True)
    content = models.TextField()


class WorkParttimer(models.Model):
    name = models.CharField(max_length=30)
    date = models.DateField()
    time = models.IntegerField()
    content = models.TextField()

class WorkOneday(models.Model):
    date = models.DateField()
    name = models.CharField(max_length=30)
    reg_num = models.CharField(max_length=30)
    pay = models.IntegerField()
    content = models.TextField()

class Document(models.Model):
    uploadFile = models.FileField(upload_to="")

class LaborCost(models.Model):
    date = models.DateField()
    department = models.CharField(max_length=10)
    rank = models.CharField(max_length=10)
    cost = models.IntegerField()



class WorkEmployee(models.Model):
    name = models.CharField(max_length=30)
    date = models.DateField()
    working = models.CharField(max_length=15)
    start = models.CharField(max_length=15)
    end = models.CharField(max_length=15)
    extra_type = models.CharField(max_length=10, blank=True, null=True)
    extra = models.IntegerField(blank=True, null=True)
    dayoff = models.IntegerField()
    annual = models.IntegerField()
    content = models.TextField()

employee/views.py
from django.shortcuts import render, redirect
from django.db.models import Count
from django.core import serializers
from django.http import HttpResponse
from django.db import connection
from main.editdate import *
from main.utils import *
from .annual import *
import pandas as pd

try:
    from io import BytesIO as IO  # for modern python
except ImportError:
    from io import StringIO as IO  # for legacy python


def employee(request):
    if request.method == "POST":
        data = getPOSTValue(request.POST)
        model = Employee.objects.filter(id=data[0])

        if len(model) == 0:
            model = Employee()
        else:
            model = Employee.objects.get(id=data[0])

        model.name = data[1]
        model.reg_num = data[2]
        model.contact = data[3]

        if data[2].split("-")[1][0] == "1" or data[2].split("-")[1][0] == "3":
            model.gender = "남"
        else:
            model.gender = "여"

        model.bank = data[5]
        model.bank_num = data[6]
        model.inwork = data[7]

        if data[8]:
            model.outwork = data[8]
        model.department = data[9]
        model.rank = data[10]
        model.worksystem = data[11]
        model.pay = data[12]
        model.insurance = data[13]
        model.health = data[14]
        model.content = data[15]
        model.notreport = data[16]

        model.save()

        return redirect("employee:employee")

    datas = Employee.objects.filter(outwork__isnull=True).all()
    context = {
        'datas': datas,
    }
    return render(request, "employee/employee.html", context)


def getemployee(request):
    key = request.GET.get("key")
    data = Employee.objects.filter(id=key)
    post_list = serializers.serialize('json', data)
    return HttpResponse(post_list, content_type="text/json-comment-filtered")


def parttimer(request):
    if request.method == "POST":
        data = getPOSTValue(request.POST)
        model = Parttimer.objects.filter(id=data[0])

        if len(model) == 0:
            model = Parttimer()
        else:
            model = Parttimer.objects.get(id=data[0])

        model.name = data[1]
        model.reg_num = data[2]
        model.contact = data[3]

        if data[2].split("-")[1][0] == "1" or data[2].split("-")[1][0] == "3":
            model.gender = "남"
        else:
            model.gender = "여"

        model.pay = data[5]
        model.bank = data[6]
        model.bank_num = data[7]
        model.department = data[8]
        model.part = data[9]
        model.inwork = data[10]
        if data[11]:
            model.outwork = data[11]
        model.health = data[12]
        model.content = data[13]
        model.notreport = data[14]

        model.save()

        return redirect("employee:parttimer")
    datas = Parttimer.objects.all()
    context = {
        'datas': datas,
    }
    return render(request, "employee/parttimer.html", context)


def getparttimer(request):
    key = request.GET.get("key")
    data = Parttimer.objects.filter(id=key)
    post_list = serializers.serialize('json', data)
    return HttpResponse(post_list, content_type="text/json-comment-filtered")


def oneday(request):
    if request.method == "POST":
        data = getPOSTValue(request.POST)
        model = Oneday.objects.filter(id=data[0])

        if len(model) == 0:
            model = Oneday()
        else:
            model = Oneday.objects.get(id=data[0])

        model.name = data[1]
        model.reg_name = data[2]
        model.contact = data[3]
        model.save()

        return redirect("employee:oneday")

    datas = Oneday.objects.all()
    context = {
        'datas': datas,
    }
    return render(request, "employee/oneday.html", context)


def getOneday(request):
    key = request.GET.get("key")
    data = Oneday.objects.filter(id=key)
    post_list = serializers.serialize('json', data)
    return HttpResponse(post_list, content_type="text/json-comment-filtered")


def manageAnnual(request):
    datas = list()
    year = request.GET.get("year", str(datetime.today().year))
    sorted = request.GET.get("sorted", "name")
    reverse = request.GET.get("reversed", 0)
    months = [f"{year}-{str(i).rjust(2, '0')}" for i in range(1, 13)]
    now = datetime.today().strftime("%Y-%m")

    #홀 - 스시 - 핫 / 즉 / 샐 - 세척
    if reverse == "1":
        if sorted == "department":
            employees = list()
            tmps = list()
            tmps.append(Employee.objects.filter(department="홀").all())
            tmps.append(Employee.objects.filter(department="스시").all())
            tmps.append(Employee.objects.filter(department="핫/즉/샐").all())
            tmps.append(Employee.objects.filter(department="세척").all())
            for tmp in tmps:
                employees.extend(tmp)
        else:
            employees = Employee.objects.all().order_by("-"+sorted)
    else:
        if sorted == "department":
            employees = list()
            tmps = list()
            tmps.append(Employee.objects.filter(department="세척").all())
            tmps.append(Employee.objects.filter(department="핫/즉/샐").all())
            tmps.append(Employee.objects.filter(department="스시").all())
            tmps.append(Employee.objects.filter(department="홀").all())
            for tmp in tmps:
                employees.extend(tmp)
        else:
            employees = Employee.objects.all().order_by(sorted)

    print(employees)
    for employee in employees:
        total = 0
        form = {
            'name': "",
            "department": "",
            "inwork": "",
            "month_1": 0,
            "month_2": 0,
            "month_3": 0,
            "month_4": 0,
            "month_5": 0,
            "month_6": 0,
            "month_7": 0,
            "month_8": 0,
            "month_9": 0,
            "month_10": 0,
            "month_11": 0,
            "month_12": 0,
            "total": 0,
        }
        form["name"] = employee.name
        form["department"] = employee.department
        form["inwork"] = employee.inwork

        for i in range(1, 13):
            a = (len(WorkStaff.objects.filter(name=employee.name, date__year=year, date__month=i, worktype="연차")) * 1)
            b = (len(WorkStaff.objects.filter(name=employee.name, date__year=year, date__month=i, worktype="반차")) * 0.5)
            total += a + b
            form["month_" + str(i)] = a + b if (a + b) > 0.0 else int(a + b)

        form["total"] = total
        datas.append(form)

    context = {
        'months': months,
        'year': year,
        'now': now,
        'datas': datas,
        'sorted': sorted,
        'reversed': reverse,
    }
    return render(request, "employee/manageAnnual.html", context)


def retired(request):
    target = request.GET.get("target", "employee")

    if target == "employee":
        datas = Employee.objects.filter(outwork__isnull=False).all()
    else:
        datas = Parttimer.objects.filter(outwork__isnull=False).all()

    context = {
        'target': target,
        'datas': datas,
    }
    return render(request, "employee/retired.html", context)


def workemployee(request):
    error = ""

    # Create Employee Data
    employees = Employee.objects.all()

    # If Don't have Employee data
    if not employees:
        return render(request, "employee/employee.html", {'error': "직원을 먼저 생성해주세요."})

    # Get Request
    requestGetEmployee = request.GET.get("employee", employees[0].name)
    requestGetDate = request.GET.get("date", datetime.now().strftime("%Y-%m"))

    year = requestGetDate.split("-")[0]
    month = requestGetDate.split("-")[1]

    if request.method == "POST":
        datas = list()

        inputName = ["workDate",
                     "workName",
                     "workType",
                     "workStart",
                     "workEnd",
                     "breakTime",
                     "workContent"]

        for name in inputName:
            datas.append(request.POST.get(name))

        if WorkStaff.objects.filter(date=datas[0], name=datas[1]):
            model = WorkStaff.objects.get(date=datas[0], name=datas[1])
        else:
            model = WorkStaff()

        model.date = datas[0]
        model.name = datas[1]
        model.worktype = datas[2]
        model.workstart = convertTimeToMinute(datas[3])
        model.workend = convertTimeToMinute(datas[4])

        if datas[5]:
            model.breaktime = convertTimeToMinute(time=datas[5], isFloat=True)
        else:
            model.breaktime = 0

        if datas[6]:
            model.content = datas[6]
        else:
            model.content = ""

        model.save()

    # Create Calendar
    calendar = getCalendar(year, month)
    workDatas = WorkStaff.objects.filter(name=requestGetEmployee, date__year=year, date__month=month)

    # Context
    context = {
        'employees': employees,
        'calendar': calendar,
        'workdatas': workDatas,

        'selectedEmployee': requestGetEmployee,
        'e': Employee.objects.filter(name=requestGetEmployee).all()[0],
        'year': year,
        'month': month,

        'error': error,
    }
    return render(request, "employee/workemployee.html", context)


def getWorkEmployee(request):
    name = request.GET.get("name")
    date = request.GET.get("date")
    data = WorkStaff.objects.filter(name=name, date=date)
    post_list = serializers.serialize('json', data)
    return HttpResponse(post_list, content_type="text/json-comment-filtered")


def workparttimer(request):
    if request.method == "POST":

        # Base Data
        name = request.POST.get("name")
        month = list(map(int, request.POST.get("month").split("-")))

        # Input Data
        dates = request.POST.getlist("dates[]")
        times = request.POST.getlist("times[]")
        contents = request.POST.getlist("contents[]")

        # target Month Data Clear
        WorkParttimer.objects.filter(name=name, date__year=month[0], date__month=month[1]).delete()

templates/employee/employee.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
    {% if error %}
        <script>alert("{{ error }}");</script>
    {% endif %}
    <div class="input-area">
        <form method="post">
            <div class="input-form">
                {% csrf_token %}
                <input type="hidden" name="id" id="id" value="-1">
                <div><label>이름</label><input type="text" name="name" id="name" required></div>
                <div><label>주민등록번호</label><input type="text" name="reg_num" id="reg_num" required></div>
                <div><label>연락처</label><input type="text" name="contact" id="contact" required></div>
                <input type="hidden" name="gender" id="gender" value="1" required>
                <div><label>은행</label><input type="text" name="bank" id="bank" required></div>
                <div><label>계좌번호</label><input type="text" name="bank_num" id="bank_num" required></div>
                <div><label>입사일</label><input type="date" name="inwork" id="inwork" required></div>
                <div><label>퇴사일</label><input type="date" name="outwork" id="outwork"></div>
                <div><label>부서</label><input type="text" name="department" id="department" required></div>
                <div><label>직급</label><input type="text" name="rank" id="rank" required></div>
                <div><label>근무제</label><input type="text" name="worksystem" id="worksystem" required></div>
                <div><label>계약임금</label><input type="number" name="pay" id="pay" required></div>
                <div><label>4대보험</label><input type="text" name="insurance" id="insurance" required></div>
                <div><label>보건증발급일</label><input type="date" name="health" id="health"></div>
                <div><label>메모</label><input type="text" name="content" id="content"></div>
                <div><label>급여신고</label>
                    <select name="notreport" id="notreport">
                        <option value="1">N</option>
                        <option value="0" selected>Y</option>
                    </select>
                </div>
            </div>
            <div class="submit-form">
                <div><input type="submit" value="저장"></div>
                <input type="button" value="삭제" id="delete">
                <div><input type="button" value="초기화" onclick="location.href='';"></div>
            </div>
        </form>
    </div>
    <div class="null-area">
    </div>
    <div class="view-area">
        <div class="view-header"><h1>직원관리</h1></div>

        <div style="border : 1px solid black; height : 35rem; overflow: auto;">
            <div id="data-fields">

            </div>
        </div>
    </div>
    <script type="text/javascript">
        var dataHeader = ["이름", "주민등록번호", "연락처", "성별", "은행", "계좌번호", "입사일",
            "부서", "직급", "근무제", "계약임금", "4대보험", "메모", "보건증발급일", "급여미신고"];
        var datas = [];
        var dataId = "#data-fields";
        var sortfix = [0, 1];
        let db = "employee";

        {% for data in datas %}
            var line = []
            line.push("{{ data.id }}");
            line.push("{{ data.name }}");
            line.push("{{ data.reg_num }}");
            line.push("{{ data.contact }}");
            line.push("{{ data.gender }}");
            line.push("{{ data.bank }}");
            line.push("{{ data.bank_num }}");
            line.push("{{ data.inwork|date:"Y-m-d" }}");
            line.push("{{ data.department }}");
            line.push("{{ data.rank }}");
            line.push("{{ data.worksystem }}");
            line.push("{{ data.pay|intcomma }} 원");
            line.push("{{ data.insurance }}");
            line.push("{{ data.content }}");
            line.push("{{ data.health }}");
            line.push("{{ data.notreport }}");
            datas.push(line);
        {% endfor %}

        gridSetting(dataId, 1);
        printDataImportColor(1, dataId, dataHeader, datas);

        $(document).on("click", ".data-header .datas", function() {
            var sortkey = $(".data-header .datas").index(this);

            if(sortkey == sortfix[0]){
                console.log("eq");
                if(sortfix[1] == 1){
                    datas = sorting(datas, sortkey);
                    sortfix[1] = 0;

                    clearlist();
                    gridSetting(dataId, 1);
                    printDataImportColor(0, dataId, dataHeader, datas);
                } else {
                    datas = sorting(datas, sortkey);
                    datas.reverse();
                    sortfix[1] = 1;

                    clearlist();
                    gridSetting(dataId, 1);
                    printDataImportColor(0, dataId, dataHeader, datas);
                }
            }else {
                datas = sorting(datas, sortkey);
                datas.reverse();
                sortfix[0] = sortkey;
                sortfix[1] = 0;

                clearlist();
                gridSetting(dataId, 1);
                printDataImportColor(0, dataId, dataHeader, datas);
            }
        });

        $(document).on("click", ".data-body", function () {
            var findkey = $(this).children("div:eq(0)");
            var key = findkey.get()[0].innerText;
            console.log(key);
            var getValue = getData(key, "{% url 'employee:getEmployee' %}");
            console.log(getValue);
            formSetData(getValue, key);
        });
    </script>
{% endblock %}

templates/employee/employeeIO.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
    {% if error %}
        <script>alert("{{ error }}");</script>
    {% endif %}
    <div class="view-area">
        <div class="view-header io"><h1>입퇴사현황</h1><button onclick="location.href='{% url "employee:IOdownload" %}';">내보내기</button></div>
        <div id="data-fields" class="employeeIO">
            <h2>입사자 현황</h2>
            <div class="employeeI">
                <div>
                    <div class="header">
                        <span>이름</span>
                        <span>주민번호</span>
                        <span>직급</span>
                        <span>파트</span>
                        <span>근무제</span>
                        <span>입사일</span>
                        <span>퇴사일</span>
                        <span>계약임금</span>
                        <span>비고</span>
                    </div>

                    {% if inworks %}
                        <div class="datas">
                            {% for inwork in inworks %}
                                <div class="data">
                                    <span>{{ inwork.name }}</span>
                                    <span>{{ inwork.reg_num }}</span>
                                    <span>{{ inwork.department }}</span>
                                    <span>{{ inwork.rank }}</span>
                                    <span>{{ inwork.worksystem }}</span>
                                    <span>{{ inwork.inwork }}</span>
                                    <span>{{ inwork.outwork|default_if_none:"-" }}</span>
                                    <span>{{ inwork.pay }}</span>
                                    <span>{{ inwork.content }}</span>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div>이 달의 입사자가 없습니다.</div>
                    {% endif %}
                </div>
            </div>
            <h2>퇴사자 현황</h2>
            <div class="employeeO">
                <div>
                    <div class="header">
                        <span>이름</span>
                        <span>주민번호</span>
                        <span>직급</span>
                        <span>파트</span>
                        <span>근무제</span>
                        <span>입사일</span>
                        <span>퇴사일</span>
                        <span>계약임금</span>
                        <span>비고</span>
                    </div>
                    {% if outworks %}
                        <div class="datas">
                            {% for outwork in outworks %}
                                <div class="data">
                                    <span>{{ outwork.name }}</span>
                                    <span>{{ outwork.reg_num }}</span>
                                    <span>{{ outwork.department }}</span>
                                    <span>{{ outwork.rank }}</span>
                                    <span>{{ outwork.worksystem }}</span>
                                    <span>{{ outwork.inwork }}</span>
                                    <span>{{ outwork.outwork }}</span>
                                    <span>{{ outwork.pay }}</span>
                                    <span>{{ outwork.content }}</span>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div>이 달의 퇴사자가 없습니다.</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            const header = ["이름", "주민번호", "직급", "파트", "근무제", "입사일", "퇴사일", "계약임금", "비고"];
        });
    </script>
{% endblock %}

templates/employee/laborcost.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
    <div>
        <!-- 부서별 인건비 기입해서 대쉬보드로 넣을거임 -->
        <!--날짜(년,월), 부서 필터 -->
        <!-- 이름 금액 -->
        <div class="input-area">
            <form method="post">
                {% csrf_token %}
                <div class="input-form">
                    <input type="hidden" id="id" name="id" value="-1">
                    <div><label>날짜</label><input type="month" data-placeholder="날짜선택" name="date" id="date" required>
                    </div>
                    <div><label>부서</label><input type="text" name="department" id="department" required></div>
                    <div><label>직급</label>
                        <select name="rank" id="rank">
                            <option value="직원">직원</option>
                            <option value="파트">파트타이머</option>
                        </select>
                    </div>
                    <div><label>금액</label><input type="text" name="cost" id="cost" required></div>
                </div>
                <div class="submit-form">
                    <input type="submit" value="저장">
                    <input type="button" value="삭제" id="delete">
                <div><input type="button" value="초기화" onclick="location.href='';"></div>
                </div>
            </form>
        </div>
        <div class="null-area">
        </div>
        <div class="view-area">
            <div class="view-header">
                <h1>부서별 인건비 입력</h1>
            </div>

            <div style="border : 1px solid black; height : 35rem; overflow: auto;">
                <div id="data-fields">

                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var dataHeader = ["날짜", "부서", "직급", "금액"];
        var datas = []
        var dataId = "#data-fields";
        let db = "laborcost";

        {% for data in datas %}
            var line = [];

            line.push("{{ data.id }}");
            line.push("{{ data.date|date:'Y년 m월' }}");
            line.push("{{ data.department }}");
            line.push("{{ data.rank }}");
            line.push("{{ data.cost|intcomma }}");
            datas.push(line)
        {% endfor %}

        gridSetting(dataId, 1);
        printData(1, dataId, dataHeader, datas);

        $(document).on("click", ".data-body", function () {
            var findkey = $(this).children("div:eq(0)");
            var key = findkey.get()[0].innerText;
            console.log(key);
            var getValue = getData(key, "{% url 'employee:getLaborCost' %}");
            console.log(getValue);
            getValue["date"] = getValue["date"].slice(0,7)
            formSetData(getValue, key);
        });
    </script>
{% endblock %}

templates/employee/manageAnnual.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% load customfilter %}
{% block content %}
    <div class="annuals-data">
        <div class="annuals-head">
            <h2>연차기록</h2>
            <form>
                <div>
                <label>년도검색</label><input type="number" name="year" min="1999" max="3000" value="{{ year }}">
                </div>
                <input type="submit" value="검색">
            </form>
        </div>
        <div>
            <span onclick="location.href='{% url "employee:manageAnnual" %}?year={{ year }}&sorted=name&reversed={% if sorted == 'name' and reversed == '1' %}0{% elif sorted == 'name' %}1{% else %}0{% endif %}'">이름</span>
            <span onclick="location.href='{% url "employee:manageAnnual" %}?year={{ year }}&sorted=department&reversed={% if sorted == 'department' and reversed == '1' %}0{% elif sorted == 'department' %}1{% else %}0{% endif %}'">부서</span>
            <span onclick="location.href='{% url "employee:manageAnnual" %}?year={{ year }}&sorted=inwork&reversed={% if sorted == 'inwork' and reversed == '1' %}0{% elif sorted == 'inwork' %}1{% else %}0{% endif %}'">입사일</span>
            <span>1월</span>
            <span>2월</span>
            <span>3월</span>
            <span>4월</span>
            <span>5월</span>
            <span>6월</span>
            <span>7월</span>
            <span>8월</span>
            <span>9월</span>
            <span>10월</span>
            <span>11월</span>
            <span>12월</span>
            <span>총계(년)</span>
        </div>
        {% if datas %}
            {% for data in datas %}
                <div>
                    <span>{{ data.name }}</span>
                    <span>{{ data.department }}</span>
                    <span {% if "today"|isBefore:data.inwork %}class="bg-warning"{% endif %}>{{ data.inwork|date:"Y-m-d" }}</span>
                    <span {% if now|isBefore:months.0 %}class="bg-before"{% endif %}>{{ data.month_1 }}</span>
                    <span {% if now|isBefore:months.1 %}class="bg-before"{% endif %}>{{ data.month_2 }}</span>
                    <span {% if now|isBefore:months.2 %}class="bg-before"{% endif %}>{{ data.month_3 }}</span>
                    <span {% if now|isBefore:months.3 %}class="bg-before"{% endif %}>{{ data.month_4 }}</span>
                    <span {% if now|isBefore:months.4 %}class="bg-before"{% endif %}>{{ data.month_5 }}</span>
                    <span {% if now|isBefore:months.5 %}class="bg-before"{% endif %}>{{ data.month_6 }}</span>
                    <span {% if now|isBefore:months.6 %}class="bg-before"{% endif %}>{{ data.month_7 }}</span>
                    <span {% if now|isBefore:months.7 %}class="bg-before"{% endif %}>{{ data.month_8 }}</span>
                    <span {% if now|isBefore:months.8 %}class="bg-before"{% endif %}>{{ data.month_9 }}</span>
                    <span {% if now|isBefore:months.9 %}class="bg-before"{% endif %}>{{ data.month_10 }}</span>
                    <span {% if now|isBefore:months.10 %}class="bg-before"{% endif %}>{{ data.month_11 }}</span>
                    <span {% if now|isBefore:months.11 %}class="bg-before"{% endif %}>{{ data.month_12 }}</span>
                    <span class="bg-success">{{ data.total }}</span>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <script>

    </script>
{% endblock %}