employee/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "employee"

urlpatterns = [
                  path('employee', views.employee, name="employee"),
                  path('employee/getemployee', views.getemployee, name="getEmployee"),

                  path('parttimer', views.parttimer, name="parttimer"),
                  path('parttimer/getparttimer', views.getparttimer, name="getParttimer"),

                  path('oneday', views.oneday, name="oneday"),
                  path('oneday/getOneday', views.getOneday, name="getOneday"),

                  path('workemployee', views.workemployee, name="workEmployee"),
                  path('workemployee/getWork', views.getWorkEmployee, name="getWorkEmployee"),

                  path('workparttimer', views.workparttimer, name="workParttimer"),

                  path('workoneday', views.workoneday, name="workoneday"),
                  path('workoneday/getWork', views.getWorkOneday, name="getworkoneday"),

                  path('workReport', views.workReport, name="workReport"),
                  path('workReport/download', views.downloadWorkReport, name="downloadWorkReport"),

                  path('manageAnnual', views.manageAnnual, name="manageAnnual"),

                  path('laborCost', views.laborCost, name="laborCost"),
                  path('laborCost/get', views.getLaborCost, name="getLaborCost"),

                  path('employeeIO', views.employeeIO, name="employeeIO"),
                  path('IOdownload', views.IOdownload, name="IOdownload"),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
    path('sales/', views.sales, name="sales"),
    path('misu_download', views.misu_download, name="misu_download"),
    path('delete', views.delete_func, name="delete"),
    path('tmp/', views.tmp, name="tmp"),
]

qooqoo_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('employee/', include("employee.urls")),
    path('trade/', include("trade.urls")),
]

trade/urls.py
from django.urls import path
from . import views

app_name = "trade"

urlpatterns = [
    path('client/', views.client, name="client"),
    path('client/getclient', views.getClient, name="getClient"),
    path('client/trade', views.clientTrade, name="clientTrade"),
    path('client/trade/get', views.getClientTrade, name="getClientTrade"),
    path('client/trade/edit', views.editTrade, name="editTrade"),
    path('client/trade/gettrade', views.getTrade, name="getTrade"),

    path('fix/', views.fix, name="fix"),
    path('fix/getFix', views.getFix, name="getFix"),
    path('fix/cost', views.fixCost, name="fixCost"),
    path('fix/cost/getCost', views.getFixCost, name="getFixCost"),

    path('manage/', views.manage, name="manage"),
    path('manage/getmanage', views.getManage, name="getmanage"),

    path('royalty/', views.royalty, name="royalty"),
    path('royalty/getRoyalty', views.getRoyalty, name="getRoyalty"),

    path('rant/', views.rant, name="rant"),
    path('rant/getrant', views.getRant, name="getRant"),
    path('rant/pay', views.rantPay, name="rantPay"),
    path('rant/pay/getRantPay', views.getRantPay, name="getRantPay"),

    path('etc/', views.etc, name="etc"),
    path('client/getetc', views.getEtc, name="getEtc"),

    path('etc/pay', views.etcPay, name="etcPay"),
    path('etc/pay/getPay', views.getEtcPay, name="getEtcPay"),

    path('cardinfo', views.cardinfo, name="cardinfo"),
    path('cardinfo/getinfo', views.getCardInfo, name="getcardinfo"),

    path('card', views.cardcost, name='cardcost'),
    path('card/getCost', views.getCardCost, name='getcardcost'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>쿠우쿠우 송천점 관리시스템</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icons" href="{% static 'img/favicon.png' %}">
    <link href="{% static 'css/root.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/default.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/navigation.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/modal.css' %}" rel="stylesheet" type="text/css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js"></script>

    <script src="{% static 'js/data.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/treeview.js' %}"></script>
</head>
<body>
{% include 'navigation.html' %}
{% block content %}
{% endblock %}
</main>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
<script>
    $(document).on("click", "#delete", function () {
        let id = $("#id").val();
        if (id > 0) delete_data(id, db, "{% url 'main:delete' %}");
    })
</script>
</body>
</html>

templates/navigation.html
{% load static %}
<header>
   <img id="header-favicon" src="{% static 'img/favicon.png' %}" width="25px"><h1>쿠우쿠우 관리시스템<span id="h1-sub">송천점</span></h1>
    <ul>
        <li><a href="{% url 'main:index' %}">대시보드</a></li>
        <li><a href="{% url 'main:sales' %}">매출관리</a></li>
    </ul>
</header>
<nav>
    <div class="scroll-wrap">
        <!-- 최상위 카테고리-->
        <ul class="first-view"> 
            <div class="ml-1">
                    <em class="ic16 ic-close"></em>
                    <em class="ic16 ic-folder"></em>
                    <span class="menu-name">거래처</span>
            </div>
            <ul class="second-view">
                <li> <!-- 하위 카테고리 -->
                    <div class="ml-1" onclick='location.href="{% url 'trade:client' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">거래처관리</span>
                    </div>
                </li>
                <li> <!-- 하위 카테고리 -->
                    <div class="ml-1" onclick='location.href="{% url 'trade:clientTrade' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">거래내역</span>
                    </div>
                </li>
            </ul>
        </ul>
        <!-- 최상위 카테고리-->
        <ul class="first-view"> 
            <div class="ml-1">
                    <em class="ic16 ic-close"></em>
                    <em class="ic16 ic-folder"></em>
                    <span class="menu-name">고정비</span>
            </div>
            <ul class="second-view">
                <!-- 하위 카테고리 -->
                <li> 
                    <div class="ml-1" onclick='location.href="{% url 'trade:fix' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">목록관리</span>
                    </div>
                </li>
                <!-- 하위 카테고리 -->
                <li> 
                    <div class="ml-1" onclick='location.href="{% url 'trade:fixCost' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">납부내역</span>
                    </div>
                </li>
            </ul>
        </ul>
        <!-- 최상위 카테고리-->
        <ul class="first-view"> 
            <div class="ml-1">
                    <em class="ic16 ic-close"></em>
                    <em class="ic16 ic-folder"></em>
                    <span class="menu-name">관리비</span>
            </div>
            <ul class="second-view">
                <!-- 하위 카테고리 -->
                <li> 
                    <div class="ml-1" onclick='location.href="{% url 'trade:manage' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">관리비관리</span>
                    </div>
                </li>
            </ul>
        </ul>
        <!-- 최상위 카테고리-->
        <ul class="first-view"> 
            <div class="ml-1">
                    <em class="ic16 ic-close"></em>
                    <em class="ic16 ic-folder"></em>
                    <span class="menu-name">로열티</span>
            </div>
            <ul class="second-view">
                <!-- 하위 카테고리 -->
                <li> 
                    <div class="ml-1" onclick='location.href="{% url 'trade:royalty' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">로열티관리</span>
                    </div>
                </li>
            </ul>
        </ul>
        <!-- 최상위 카테고리-->
        <ul class="first-view"> 
            <div class="ml-1">
                    <em class="ic16 ic-close"></em>
                    <em class="ic16 ic-folder"></em>
                    <span class="menu-name">임대료</span>
            </div>
            <ul class="second-view">
                <!-- 하위 카테고리 -->
                <li> 
                    <div class="ml-1" onclick='location.href="{% url 'trade:rant' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">임대차정보</span>
                    </div>
                </li>
                <!-- 하위 카테고리 -->
                <li> 
                    <div class="ml-1" onclick='location.href="{% url 'trade:rantPay' %}";'>
                        <em class="ic16 ic-star-on" ></em>
                        <span class="menu-name">납부내역</span>
                    </div>
                </li>
            </ul>
        </ul>

        <ul class="first-view">
            <div class="ml-1">
                    <em class="ic16 ic-close"></em>
                    <em class="ic16 ic-folder"></em>
                    <span class="menu-name">카드관리</span>
            </div>
            <ul class="second-view">
                <!-- 하위 카테고리 -->
                <li>
                    <div class="ml-1" onclick='location.href="{% url 'trade:cardinfo' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">카드정보관리</span>
                    </div>
                </li>
                <!-- 하위 카테고리 -->
                <li>
                    <div class="ml-1" onclick='location.href="{% url 'trade:cardcost' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">카드내역관리</span>
                    </div>
                </li>
            </ul>
        </ul>
        <!-- 최상위 카테고리-->
        <ul class="first-view"> 
            <div class="ml-1">
                    <em class="ic16 ic-close"></em>
                    <em class="ic16 ic-folder"></em>
                    <span class="menu-name">기타</span>
            </div>
            <ul class="second-view">
                <!-- 하위 카테고리 -->
                <li> 
                    <div class="ml-1" onclick='location.href="{% url 'trade:etc' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">기타목록</span>
                    </div>
                </li>
                <!-- 하위 카테고리 -->
                <li> 
                    <div class="ml-1" onclick='location.href="{% url 'trade:etcPay' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">납부내역</span>
                    </div>
                </li>
            </ul>
        </ul>
        <!-- 최상위 카테고리-->
        <ul class="first-view"> 
            <div class="ml-1">
                    <em class="ic16 ic-close"></em>
                    <em class="ic16 ic-folder"></em>
                    <span class="menu-name">근로자정보</span>
            </div>
            <ul class="second-view">
                <!-- 하위 카테고리 -->
                <li> 
                    <div class="ml-1" onclick='location.href="{% url 'employee:employee' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">직원</span>
                    </div>
                </li>
                <!-- 하위 카테고리 -->
                <li> 
                    <div class="ml-1" onclick='location.href="{% url 'employee:parttimer' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">파트타이머</span>
                    </div>
                </li>
                <!-- 하위 카테고리 -->
                <li> 
                    <div class="ml-1" onclick='location.href="{% url 'employee:oneday' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">일용직</span>
                    </div>
                </li>
                <!-- 하위 카테고리 -->
                <li>
                    <div class="ml-1" onclick='location.href="{% url 'employee:employeeIO' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">입퇴사현황</span>
                    </div>
                </li>
            </ul>
        </ul>                           
        <ul class="first-view"> 
            <div class="ml-1">
                    <em class="ic16 ic-close"></em>
                    <em class="ic16 ic-folder"></em>
                    <span class="menu-name">근태관리</span>
            </div>
            <ul class="second-view">
                <!-- 하위 카테고리 -->
                <li> 
                    <div class="ml-1" onclick='location.href="{% url 'employee:workEmployee' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">직원</span>
                    </div>
                </li>
                <!-- 하위 카테고리 -->
                <li> 
                    <div class="ml-1" onclick='location.href="{% url 'employee:workParttimer' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">파트타이머</span>
                    </div>
                </li>
                <!-- 하위 카테고리 -->
                <li> 
                    <div class="ml-1" onclick='location.href="{% url 'employee:workoneday' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">일용직</span>
                    </div>
                </li>
                <!-- 하위 카테고리 -->
                <li>
                    <div class="ml-1" onclick='location.href="{% url 'employee:workReport' %}";'>
                        <em class="ic16 ic-star-on"></em>
                        <span class="menu-name">근태레포트</span>
                    </div>
                </li>
            </ul>
        </ul>
        <ul class="first-view">
            <!-- 하위 카테고리 -->
            <div class="ml-1" onclick='location.href="{% url 'employee:laborCost' %}";'>
                <em class="ic16 ic-star-on"></em>
                <span class="menu-name">월별인건비기입</span>
            </div>
        </ul>
        <ul class="first-view">
            <!-- 하위 카테고리 -->
            <div class="ml-1" onclick='location.href="{% url 'employee:manageAnnual' %}";'>
                <em class="ic16 ic-star-on"></em>
                <span class="menu-name">연차관리대장</span>
            </div>
        </ul>
    </div>
</nav>
<main>